### ISSUE TITLE
不设置例外路径时，监控无效，所有操作都被pass

### ISSUE THREAD

**Issue by moyuwa** [TheKingOfDuck/FileMonitor#2]
运行fileMonitor.py文件
当Unnecessary directory不设置任何路径时，下面语句
 if doWithout in event.src_path:
            pass
始终成立，所有操作都被pass

**Comment by TheKingOfDuck** [comment]
> 运行fileMonitor.py文件
> 当Unnecessary directory不设置任何路径时，下面语句
> if doWithout in event.src_path:
> pass
> 始终成立，所有操作都被pass

该bug已修复，感谢大哥对项目的大力支持。

然后我看了下大哥写的加强的版本，有两bug, 第一是文件移动时只显示了源路径，没显示复制到哪儿了。第二是是否显示文件夹变化设置无效。我在大哥的版本是修复了这两问题，并加了参数传值，二进制文件优化等。

一键安装：
```
python3 -m pip install filemon==1.1 -i https://pypi.python.org/simple/
filemon -h
```
