### ISSUE TITLE
main.py有些问题修改检测不到。

### ISSUE THREAD

**Issue by komomon** [TheKingOfDuck/FileMonitor#4]
我指定了一个监控目录E:\Web，这个目录的子目录的子目录下面的txt修改ctrl+s保存后检测不到文件变化。
初始状态：
![image](https://user-images.githubusercontent.com/52700174/107970260-da930d00-6feb-11eb-8636-e48181f54d33.png)
修改后：
![image](https://user-images.githubusercontent.com/52700174/107970319-ef6fa080-6feb-11eb-8dd3-58c690d46b79.png)

**Comment by TheKingOfDuck** [comment]
> 我指定了一个监控目录E:\Web，这个目录的子目录的子目录下面的txt修改ctrl+s保存后检测不到文件变化。
> 初始状态：
> ![image](https://user-images.githubusercontent.com/52700174/107970260-da930d00-6feb-11eb-8636-e48181f54d33.png)
> 修改后：
> ![image](https://user-images.githubusercontent.com/52700174/107970319-ef6fa080-6feb-11eb-8dd3-58c690d46b79.png)

核心文件是fileMonitor.py 优先使用  main.py只是个demo
